junit test code for hashcode and equals method
ykgautam/java-examples pull request #3
Opened 2021-01-04 15:24 UTC by ykgautam

2021-01-04 22:49 UTC, Ganeshgautam commented on java-examples/src/main/java/edu/practice/hashequals/Human.java
> +	int adharNumber ;
why not private?
```suggestion
	private int adharNumber ;
```

2021-01-04 22:49 UTC, Ganeshgautam commented on java-examples/src/main/java/edu/practice/hashequals/Human.java
> +	String name;
```suggestion
	private String name;
```

2021-01-04 22:50 UTC, Ganeshgautam commented on java-examples/src/main/java/edu/practice/hashequals/Human.java
> +//			System.out.println("fff");
remove all commented out code.

2021-01-04 23:12 UTC, Ganeshgautam requested changes

2021-01-04 23:12 UTC, Ganeshgautam commented on java-examples/src/test/java/edu/practice/hashequals/HumanTest.java
> +	static private int adharNo1 = 111;
why static? 
also you should keep following order if there is some requirement for static:
`private static SomeType someField;`

2021-01-04 23:12 UTC, Ganeshgautam commented on java-examples/src/test/java/edu/practice/hashequals/HumanTest.java
> +	static String name2 = "yash";
remove static from all these fields.

2021-01-04 23:12 UTC, Ganeshgautam commented on java-examples/src/test/java/edu/practice/hashequals/HumanTest.java
> +	void testHashcode() {
Add more cases for null cases, empty name and with human2 as null.

2021-01-05 05:26 UTC, ykgautam commented
If I make adharNumber as private den I can't get that number in test
class.. scope visibility kam ho jati
 Protected bana k chal jata hai

On Tue, 5 Jan 2021, 4:19 am Ganesh Gautam, <notifications@github.com> wrote:

> *@Ganeshgautam* commented on this pull request.
> ------------------------------
>
> In java-examples/src/main/java/edu/practice/hashequals/Human.java
> <https://github.com/ykgautam/java-examples/pull/3#discussion_r551615015>:
>
> > @@ -0,0 +1,43 @@
>
> +package edu.practice.hashequals;
>
> +
>
> +public class Human {
>
> +	
>
> +	int adharNumber ;
>
>
> why not private?
> ⬇️ Suggested change
>
> -	int adharNumber ;
>
> +	private int adharNumber ;
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ykgautam/java-examples/pull/3#pullrequestreview-561402537>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMJDADI4Y5NTIOEOHISY7ZTSYJAYRANCNFSM4VTFFODQ>
> .
>

2021-01-05 08:32 UTC, merged

2021-01-06 13:06 UTC, Ganeshgautam commented
> If I make adharNumber as private den I can't get that number in test class.. scope visibility kam ho jati Protected bana k chal jata hai
> […](#)

what happened to abstraction? 
Expose a getter and make the fields private.

2021-01-06 13:38 UTC, ykgautam commented
okay.. i will do this creating getter method for it